Completed es6-template-literals. | Rakesh
bhaisingh/m2-0621-code-solutions pull request #11
Opened 2021-07-27 09:37 UTC by bhaisingh

![image](https://user-images.githubusercontent.com/20628519/127132308-59be4e8c-4567-4cd6-818c-e35a582fe579.png)

2021-07-27 18:18 UTC, TimelikeClosure requested changes

2021-07-27 18:18 UTC, TimelikeClosure commented on es6-template-literals/index.html
> +    console.log(`LearningFuze: ${address}`);
Please sure you are A) converting _all_ concatenation operations to template literals, and B) not modifying other parts of the code.

---

![image](https://user-images.githubusercontent.com/16143771/127206909-d3b4cd4d-e37b-4400-9886-6ece7656a6ed.png)

---

![image](https://user-images.githubusercontent.com/16143771/127206928-a3b3b6ee-cad8-4dea-8493-eb37c08be8ad.png)

2021-07-28 00:19 UTC, bhaisingh commented
![image](https://user-images.githubusercontent.com/20628519/127243793-caab5512-16a4-4ed9-b495-2346dcc468ab.png)

2021-07-28 02:06 UTC, TimelikeClosure approved these changes

2021-07-28 02:32 UTC, merged